import "./App.css"

export default function Bai6() {
  return (
    <div className="w-[500px] h-[500px] overflow-auto" >
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem velit inventore, repellendus asperiores facere explicabo facilis incidunt debitis quia provident, culpa maxime nisi non delectus tempore distinctio ducimus unde. Praesentium.
        Impedit natus sed quas et nam consequuntur deleniti neque obcaecati excepturi! Nam, nobis laborum id quod soluta maiores quam libero maxime odit ducimus minima, nihil nisi, officiis qui quisquam recusandae.
        Facilis vel aspernatur, soluta dolor dicta repellat dolorum voluptatum tempora delectus tenetur, magnam expedita explicabo sed impedit modi. Error non eaque neque eligendi dolores quae unde, temporibus ratione reprehenderit ad.
        Itaque veritatis corrupti minima ipsa repellendus accusamus, aperiam esse aliquam, dignissimos atque odit praesentium animi numquam nam! Explicabo ad accusamus adipisci voluptas laboriosam corrupti, rerum incidunt commodi voluptatem minus doloribus?
        Illo soluta et eum facere ducimus nam, maxime commodi, deserunt distinctio, pariatur ad laudantium labore aliquam facilis dolorem voluptatibus molestias harum id omnis dolore possimus officia cumque. Nam, distinctio voluptatum!
        Dignissimos, molestias! Magni tempora animi expedita, doloremque ullam voluptatibus dicta sit? Repudiandae eos commodi tempora voluptatem incidunt iste odit voluptatum, aut, eum aliquam, voluptatibus sint ipsam aliquid repellat quaerat eius.
        Placeat pariatur obcaecati accusamus corporis iure, excepturi commodi voluptas beatae suscipit et modi quidem. Voluptatibus sint quisquam aut totam laborum illum magni! Harum nulla corporis in ullam eaque repellat enim.
        Explicabo, non eveniet. Aliquam voluptates odio eum dolorem distinctio repudiandae harum, facilis, delectus voluptatibus quis, deleniti hic dolor. Quas atque odit repudiandae facere sequi, placeat modi tempora eaque ad illum.
        Dolore ex, earum officiis nisi sit nesciunt. Hic itaque atque libero, praesentium nemo veniam tempora excepturi repellat corrupti vitae voluptatum distinctio perspiciatis similique unde consequatur beatae quis ratione, laudantium sapiente?
        Minima ipsum nostrum ullam tempore voluptatum vel cupiditate esse officiis nisi, quod voluptate, beatae error saepe. Harum, est iure provident pariatur nostrum quibusdam quo inventore, nobis recusandae id aperiam veritatis.
        Sit dolores, deleniti nesciunt sunt voluptatibus quaerat! Saepe voluptates at molestiae, aut cumque delectus deserunt, vel perspiciatis animi placeat, dignissimos voluptatum odit voluptas dolore maiores harum officiis nulla repellat omnis.
        Modi adipisci mollitia voluptatem earum perspiciatis impedit iste possimus fuga quia, corporis enim vitae! Voluptates explicabo sequi, molestias placeat eaque dolores sapiente sit nemo ut rem, molestiae quos deleniti dolorum?
        Sint iste voluptates, soluta dolorem libero ea ex, iure eos doloribus porro a tempora quas officiis obcaecati nobis beatae veniam repudiandae, ullam odio quos debitis sapiente eligendi. Repudiandae, neque dicta?
        Ipsa molestias sunt deleniti maxime eaque velit nemo nisi aspernatur inventore nulla, tenetur explicabo non dolorem a hic porro quae, commodi sit. Sapiente perspiciatis necessitatibus eos nesciunt doloremque delectus quibusdam?
        Suscipit exercitationem iure expedita soluta veniam rem sint cupiditate fuga ullam laboriosam voluptatum eos eveniet et ad minima ipsam, debitis nihil dicta provident rerum minus! Deserunt, eius? Dolor, a numquam.
        Quia tempore, eaque saepe aperiam repellat delectus veniam. Architecto voluptates autem esse, aliquam ullam, et a quos veniam provident nobis laboriosam ipsam illo mollitia, obcaecati in nulla minima inventore cum.
        Qui, perferendis enim? Eaque rerum mollitia maiores nihil architecto, deserunt minus perspiciatis eum facere sequi blanditiis nesciunt similique. Reprehenderit nobis sint placeat quam nostrum odit dignissimos nesciunt sequi, est tempora.
        Dolorum tenetur, ullam unde veritatis dolores asperiores sequi laboriosam voluptate! Minus tenetur eaque quos dolor sint? Quibusdam quisquam, saepe nemo ab ipsam doloremque labore. Vel dignissimos vitae quisquam nobis in.
        Fugit eligendi neque dolorum quisquam. Nihil, voluptatibus dolorum optio veritatis saepe dignissimos, et sint quo, inventore corporis tempore neque voluptate architecto minima perferendis. Nostrum dolores deserunt repellendus minus sequi libero?
        Minus eum nisi provident odit quasi ipsam optio totam similique perferendis hic dicta culpa laudantium, praesentium amet! Voluptates architecto unde vitae rem repudiandae officiis sequi distinctio quasi. Ducimus, perferendis molestias.
        Ipsa vero quam quos consequuntur consequatur ad ratione repudiandae alias tenetur accusamus! Consectetur accusamus suscipit ex omnis beatae modi, quo officiis ad! Culpa deserunt perferendis quisquam mollitia in velit excepturi.
        Recusandae, ad cum deleniti tempore et perferendis inventore voluptatibus illo rerum doloremque adipisci illum praesentium deserunt facere sit alias magni necessitatibus fugiat asperiores esse numquam consequatur. Perspiciatis reprehenderit explicabo molestias.
        Voluptatum, quo, est mollitia eos consequatur itaque beatae eum explicabo autem praesentium corrupti sint natus delectus libero dolores voluptates dolorum ratione! Voluptatibus laborum sunt esse, nemo repellat ipsam tempora officiis?
        Dolores illum dolorem est nemo similique provident. Nemo veniam maxime illum sequi, voluptate dicta repellendus mollitia porro excepturi saepe nam accusantium qui nesciunt est atque animi cum dignissimos iste ducimus.
        Explicabo harum quia, impedit sunt libero, culpa voluptatem inventore ea nobis corporis facilis quos ipsum doloremque ut voluptatibus similique? Assumenda maiores totam obcaecati laudantium ipsa perferendis voluptate dolor magnam fugiat?
        Facilis deserunt doloribus, quo minima suscipit, quidem deleniti totam odio reiciendis ab impedit nemo earum optio! Consectetur beatae repellendus quis fuga adipisci perspiciatis, id, asperiores, corporis laboriosam neque sequi possimus!
        Dolor velit provident rerum iusto culpa dicta labore, nulla qui ratione, sed repellendus eos quod, debitis fugiat ad. Dignissimos, facilis ratione. Fugiat eum numquam, culpa sint dolores ex vero reiciendis.
        Facere quidem praesentium pariatur reprehenderit tempore enim eius nemo nulla. Tempora rem incidunt, consectetur odit, molestiae placeat voluptates quae maiores facere illum quia modi dolores dicta magnam eveniet, fugit cumque.
        Porro expedita laboriosam commodi dolor quisquam temporibus inventore! Rerum laborum similique adipisci! Illum distinctio accusantium dicta recusandae amet, a consequatur error quia! A corporis deserunt ex vel aliquid, sequi in.
        Est velit, maiores dolor animi ad commodi consequatur, magni quidem laborum quod quibusdam fugit in soluta! Fugit consequatur, quia dolorum, quod eos magni, aliquid earum ratione facere sed neque quo?
        Modi consequuntur recusandae eaque perferendis iure nihil. Dolor sint asperiores possimus aliquam nulla saepe recusandae cum, voluptates, et odio odit provident enim dolores unde nesciunt soluta quidem perferendis corrupti hic?
        Cupiditate quae perspiciatis amet temporibus repellendus nulla labore, dolores suscipit illum reprehenderit optio illo explicabo maiores libero perferendis ipsa facere modi consequatur atque sequi eligendi corrupti molestias eum exercitationem. Ab.
        Ratione tempora incidunt, repellendus recusandae suscipit neque deleniti asperiores deserunt voluptas sit repudiandae eius praesentium facere consectetur non enim dolores, earum corporis quia sint. Vel cum incidunt praesentium porro necessitatibus!
        Cupiditate molestiae veritatis aliquid laboriosam sed quam rerum consequuntur maxime quasi accusamus distinctio, provident saepe minima dolore! Voluptatem at consequatur velit, quas nihil dolorum placeat ipsam, esse rerum molestias accusantium.
        Tempore voluptas mollitia nobis maxime beatae, culpa aliquam qui eius quod cum eum maiores animi at deleniti harum numquam. Illum asperiores suscipit labore exercitationem cumque optio modi possimus incidunt accusamus?
        Non odit, omnis fugit nulla quibusdam facilis quidem eum quo accusamus aliquid at dolorum cumque eius provident debitis consequuntur nisi hic totam sapiente eaque dolorem! Optio fuga ratione odit numquam.
        Aspernatur ab, commodi enim autem cumque quas cupiditate reprehenderit natus nostrum iusto officiis, similique repellat incidunt velit iure magnam odio, ad reiciendis quibusdam accusantium. Distinctio enim itaque quidem rerum alias.
        Veniam quam incidunt qui molestias quidem aliquam fugiat quaerat dolores suscipit saepe pariatur ipsum recusandae, reprehenderit voluptate excepturi quis nisi aut eligendi eaque iure. Provident sed pariatur quos corporis ullam?
        Recusandae eum quod aliquid amet, harum reiciendis vel, reprehenderit cum, debitis doloremque libero rerum fugiat quam ipsam sed neque ea velit? Sapiente esse illum necessitatibus eaque, doloremque quidem laboriosam accusantium.
        Odio laborum a impedit corrupti obcaecati et repellat quae voluptate recusandae repellendus atque earum quis amet illum possimus illo adipisci iste neque ut, nostrum, facilis ullam cum magnam. Magnam, error.
        Quos alias ab nulla numquam architecto quo animi ipsam officia sint, reiciendis quasi, voluptates dolor vel unde! Deserunt saepe est sit aliquid ratione? Similique praesentium optio ab. Quas, minima reiciendis?
        Perspiciatis sint corporis dolorem amet iure earum laudantium maxime, sed quo modi mollitia impedit repellendus neque atque dignissimos voluptas voluptatibus natus ipsum quos similique cum vel? Tenetur laboriosam rem laudantium.
        Dolorum iure assumenda beatae quisquam architecto magnam amet, corporis dolores eos ut a ea similique numquam animi expedita quidem itaque unde culpa quaerat maxime voluptas. Rerum eius veniam nihil libero!
        Dolorum consequatur quo vitae molestiae ipsa praesentium non aliquam odit dignissimos distinctio esse nobis ex tempora dolor, doloremque porro sapiente voluptate quos minus officia nam quidem? Aspernatur consequuntur inventore neque?
        Porro ipsa fuga repudiandae autem, quas ut maxime sed rem aut, ducimus, reprehenderit mollitia! Consequuntur debitis tempora est saepe modi provident quaerat autem deleniti. Esse dolores quidem perspiciatis ipsam architecto.
        Quasi optio culpa, alias laborum possimus tempora nobis cupiditate molestiae accusamus quam illo sapiente repellendus doloribus nesciunt accusantium unde nemo, facilis natus vel dicta dolorum quisquam. Praesentium exercitationem natus excepturi.
        Labore error illum voluptates autem quae ex a ipsam eos distinctio quis eius laborum nam in minus consequuntur, similique et tempora repellat! Earum quisquam in nihil molestiae dolorum deleniti consectetur?
        Ipsam, expedita recusandae eveniet mollitia corrupti accusamus, laborum itaque, modi reprehenderit natus laudantium numquam quod quia quos nemo tempora! Maiores, ullam praesentium! Quia fugiat eos cupiditate. Enim dicta alias maxime.
        Cupiditate dolorum non id praesentium architecto tenetur consequatur illum sint temporibus culpa fuga, sapiente deserunt, vitae maiores accusamus in sed assumenda provident quod dolores earum. Consequatur pariatur nemo voluptate hic?
        Recusandae dignissimos libero id sapiente quam sunt, officiis perspiciatis, quaerat minima veniam deleniti commodi nulla fugit, saepe velit vitae aliquid debitis eaque ducimus consequatur quisquam aut dolores. Laboriosam, sit hic.
    </div>
  )
}
